<template>
  <div class="box" style="width:1200px;margin:0 auto;padding-top:56px;">
      <body style="tab-interval:2pt;text-justify-trim:punctuation;" ><!--StartFragment--><div class="Section0"  style="layout-grid:15.6000pt;" ><p class=MsoNormal  align=center  style="text-align:center;" ><a name="_Hlk12021119" ></a><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:14.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >【权易宝资产数字化服务平台】</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:14.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  align=center  style="text-align:center;" ><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:14.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >隐私政策</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:14.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  align=center  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-align:center;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >版本生效时间：【</font>2019<font face="宋体" >年</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;
mso-font-kerning:1.0000pt;" >11</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >月</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:10.5000pt;
mso-font-kerning:1.0000pt;" >5</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:10.5000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >日】</font></span><i><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-style:italic;font-size:10.5000pt;mso-font-kerning:1.0000pt;" ></span></i></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >上海易涟信息技术有限公司（以下称为</font>&#8220;<font face="宋体" >我们</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >或</font><font face="Times New Roman" >&#8220;</font><font face="宋体" >易涟信息</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >）系【权易宝资产数字化服务平台】</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >（以下简称</font>&#8220;<font face="宋体" >权易宝服务平台</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >或</font><font face="Times New Roman" >&#8220;</font><font face="宋体" >平台</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >）官网（网址：</font><font face="Times New Roman" >https://www.e-pex.com/index</font><font face="宋体" >的所有者和管理运营方，注册成为权易宝用户（以下简称</font><font face="Times New Roman" >&#8220;</font><font face="宋体" >您</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >或</font><font face="Times New Roman" >&#8220;</font><font face="宋体" >用户</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >）时请务必仔细阅读以下条款。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们非常重视用户个人信息及隐私权的保护，因此我们制订了涵盖如何收集、存储、使用、共享和保护用户信息以及我们为您提供的访问、更新、删除和保护这些信息方式的隐私政策。我们希望通过</font></span><b><u><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;text-decoration:underline;text-underline:single;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >《隐私政策》</font></span></u></b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >（以下简称</font>&#8220;<font face="宋体" >本隐私政策</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >或</font><font face="Times New Roman" >&#8220;</font><font face="宋体" >本政策</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >）向您清晰地介绍我们对您个人信息及其他信息的处理方式。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.1000pt;
mso-char-indent-count:2.0000;" ><b><u><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;text-decoration:underline;text-underline:single;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >权易宝服务平台中可能含有第三方产品或服务的链接或信息。如果您将个人信息填写在其他平台上或通过第三方提交</font>/<font face="宋体" >发布，则该方可能会获知您的信息。该第三方可能有其相应的服务条款及隐私政策规定，请您仔细阅读其条款，并在提供个人信息前请谨慎考虑。本隐私政策仅适用于我们所收集的信息，并不适用于任何第三方向您提供服务和收集使用信息的行为，我们无法控制第三方的行为，因此对任何第三方收集、使用您信息的行为不承担任何责任。</font></span></u></b><b><u><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;text-decoration:underline;text-underline:single;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></u></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >本隐私政策与您使用权易宝</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >服务</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >平台的服务息息相关，</font></span><b><u><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;text-decoration:underline;text-underline:single;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >请您在使用权易宝</font></span></u></b><b><u><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-weight:bold;
text-decoration:underline;text-underline:single;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >服务</font></span></u></b><b><u><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;text-decoration:underline;text-underline:single;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >平台服务前，完整阅读并透彻理解本隐私政策（尤其是加粗划线的内容）并确定了解我们对您个人信息（定义见下文）及其他信息的处理规则，并相应作出您认为适当的选择。</font></span></u></b><b><u><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;text-decoration:underline;text-underline:single;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></u></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" >&nbsp;</span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:0.0000pt;mso-outline-level:1;mso-list:l0 level1 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >一、<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们如何收集和使用您的个人信息</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >个人信息是指以电子或者其他方式记录的能够单独或者与其他信息结合识别特定自然人身份或若反映特定自然人活动情况的各种信息。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们的服务包括如下核心功能，这些功能包含了通过平台进行资产交易的功能、改进我们的服务所必须的功能及保障交易安全所必须的功能。我们可能会收集、保存和使用下列与您有关的信息才能实现上述这些功能。如果您不提供相关信息，您将无法享受我们提供的服务。这些功能包括：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:7.1000pt;mso-para-margin-bottom:0.5000gd;
text-indent:24.0000pt;mso-char-indent-count:2.0000;mso-list:l1 level3 lfo2;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >1.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >用户注册</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >您首先需要注册一个我们平台账户成为平台用户。</font></span><b><u><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;text-decoration:underline;text-underline:single;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >您注册账户时同意我们收集您的个人基本信息，包括但不限于您的姓名、手机号、电子邮箱地址、创建的用户名和密码、身份证号、银行卡卡号、身份证正反面图片等；我们将通过验证银行卡卡号、身份证正反面图片、身份证号、手机验证码的方式进行用户身份的实名验证。</font></span></u></b><b><u><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;text-decoration:underline;text-underline:single;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></u></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:7.1000pt;mso-para-margin-bottom:0.5000gd;
text-indent:24.0000pt;mso-char-indent-count:2.0000;mso-list:l1 level3 lfo2;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >2.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >用户进行资产交易</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=27  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >您在进行资产交易的过程中，我们将自动收集您在平台上的操作行为记录，并调取您在平台注册时提供的个人基本信息用于验证身份的真实性。您知悉并同意我们收集、使用用户的操作行为记录是提供在线资产交易平台服务所必要的条件。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:7.1000pt;mso-para-margin-bottom:0.5000gd;
text-indent:24.0000pt;mso-char-indent-count:2.0000;mso-list:l1 level3 lfo2;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >3.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >改进我们的服务所必须的功能</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >为更加充分地了解您的情况以便向您提供服务及提升服务质量，您同意并授权我们通过包括但不限于以下方式披露及使用您的信息：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >通过【手机号、电子邮件、站内信】等方式向您发送资产信息、交易状态通知、营销活动或其他商业性电子信息。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:0.0000pt;mso-outline-level:1;mso-list:l0 level1 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >二、<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们如何共享、转让、公开披露您的个人信息</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（一）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >共享</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们不会与</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >易涟信息</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >以外的任何公司、组织和个人分享您的个人信息，但以下情况除外：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo3;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >1.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >在获取明确同意的情况下共享：获得您的明确同意后，我们会与其他方共享您的个人信息。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo3;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >2.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们可能会根据法律法规规定，或按政府主管部门的强制性要求，对外共享您的个人信息。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo3;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >3.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >与我们的关联公司共享：您的个人信息可能会与我们的关联公司共享。我们只会共享必要的个人信息，且受本隐私政策中所声明目的的约束。关联公司如要改变个人信息的处理目的，将再次征求您的授权同意。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们的关联公司包括：【绿地金融投资控股集团有限公司、绿地控股集团有限公司、</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >上海绿地青城置业有限公司、</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >上海绿地康养养老服务有限公司、河南绿东置业有限公司等</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >及不限于未在上述公司之外的我们的关联公司</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >】。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >1.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >与授权合作伙伴共享：仅为实现本政策中声明的目的，我们的某些服务将由授权合作伙伴提供。我们可能会与合作伙伴共享您的某些个人信息，以提供更好的客户服务和用户体验。我们仅会出于合法、正当、必要、特定、明确的目的共享您的个人信息，并且只会共享提供服务所必要的个人信息。我们的合作伙伴无权将共享的个人信息用于任何其他用途。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >目前我们的授权合作伙伴包括：提供资产勘测服务的机构、资产</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >经营者</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >、提供在线签署交易合同服务的</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >数字认证</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >服务机构、其他外部协助方等。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >对我们与之共享个人信息的公司、组织和个人，我们会与其签署严格的保密协定，要求他们按照我们的说明、本隐私政策以及其他任何相关的保密和安全措施来处理个人信息。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（二）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >转让</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们不会将您的个人信息转让给任何公司、组织和个人，但以下情况除外：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >2.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >在获取明确同意的情况下转让：获得您的明确同意后，我们会向其他方转让您的个人信息；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >3.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >在涉及合并、收购或破产清算时，如涉及个人信息转让，我们会在要求新的持有您个人信息的公司、组织继续受此隐私政策的约束，否则我们将要求该公司、组织重新向您征求授权同意。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（三）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >公开披露</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们仅会在以下情况下，公开披露您的个人信息：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >4.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >获得您明确同意后；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >5.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >基于法律的披露：在法律、法律程序、诉讼或政府主管部门强制性要求的情况下，我们可能会公开披露您的个人信息。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:0.0000pt;mso-outline-level:1;mso-list:l0 level1 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >三、<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们如何保护您的个人信息</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >6.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们已使用符合业界标准的安全防护措施保护您提供的个人信息，防止数据遭到未经授权访问、公开披露、使用、修改、损坏或丢失。我们会采取一切合理可行的措施，保护您的个人信息。例如，在您的浏览器与</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >平台</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >之间交换数据时受</font>SSL<font face="宋体" >加密保护；我们同时对</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >权易宝资产数字化服务平台</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >网站提供</font>https<font face="宋体" >安全浏览方式；我们会使用加密技术确保数据的保密性；我们会使用受信赖的保护机制防止数据遭到恶意攻击；我们会部署访问控制机制，确保只有授权人员才可访问个人信息；以及我们会举办安全和隐私保护培训课程，加强员工对于保护个人信息重要性的认识。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >7.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们会采取一切合理可行的措施，确保未收集无关的个人信息。我们只会在达成本政策所述目的所需的期限内保留您的个人信息，除非需要延长保留期或受到法律的允许。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >8.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >互联网环境并非百分之百安全，我们将尽力确保或担保您发送给我们的任何信息的安全性。如果我们的物理、技术或管理防护设施遭到破坏，导致信息被非授权访问、公开披露、篡改或毁坏，导致您的合法权益受损，我们将承担相应的法律责任。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >9.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >在不幸发生个人信息安全事件后，我们将按照法律法规的要求，及时向您告知：安全事件的基本情况和可能的影响、我们已采取或将要采取的处置措施、您可自主防范和降低风险的建议、对您的补救措施等。我们将及时将事件相关情况以邮件、信函、电话、推送通知等方式告知您，难以逐一告知个人信息主体时，我们会采取合理、有效的方式发布公告。同时，我们还将按照监管部门要求，主动上报个人信息安全事件的处置情况。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:0.0000pt;mso-outline-level:1;mso-list:l0 level1 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >四、<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >您的权利</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >按照中国相关的法律、法规、标准，以及其他国家、地区的通行做法，我们保障您对自己的个人信息行使以下权利：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（一）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >访问您的个人信息</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >您有权访问您的个人信息，法律法规规定的例外情况除外。如果您想行使数据访问权，可以通过以下方式自行访问：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >账户信息</font>&#8212;&#8212;<font face="宋体" >如果您希望访问或编辑您的账户中的个人资料信息、更改您的登录或转让密码、添加安全信息等，您可以通过访问个人资料图标执行此类操作。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果您无法通过上述链接访问这些个人信息，您可以随时使用我们的</font>Web<font face="宋体" >表单联系，或发送电子邮件至【</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" >service@e-pex.com</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >】。我们将在</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" >3</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >天内回复您的访问请求。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >对于您在使用我们的服务过程中产生的其他个人信息，只要我们不需要过多投入，我们会向您提供。如果您想行使数据访问权，请发送电子邮件至【</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" >service@e-pex.com</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >】。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（二）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >更正您的个人信息</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >当您发现我们处理的关于您的个人信息有错误时，您有权要求我们做出更正。您可以通过</font>&#8220;<font face="宋体" >（一）访问您的个人信息</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >中罗列的方式提出更正申请。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果您无法通过上述链接更正这些个人信息，您可以随时使用我们的</font>Web<font face="宋体" >表单联系，或发送电子邮件至</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" >service@e-pex.com</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >。我们将在</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" >3</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >天内回复您的更正请求。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（三）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >删除您的个人信息</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >在以下情形中，您可以向我们提出删除个人信息的请求：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >10.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果我们处理个人信息的行为违反法律法规；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >11.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果我们收集、使用您的个人信息，却未征得您的同意；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >12.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果我们处理个人信息的行为违反了与您的约定；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >13.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果您不再使用我们的服务，或您注销了账号；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >14.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果我们不再为您提供服务</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >若我们决定响应您的删除请求，我们还将同时通知从我们获得您的个人信息的实体，要求其及时删除，除非法律法规另有规定或这些实体获得您的独立授权。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >当您从我们的服务中删除信息后，我们可能不会立即备份系统中删除相应的信息，但会在备份更新时删除这些信息。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（四）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >改变您授权同意的范围</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >每个业务功能需要一些基本的个人信息才能得以完成（见本政策</font>&#8220;<font face="宋体" >第一部分</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >）。对于额外收集的个人信息的收集和使用，您可以随时给予或收回您的授权同意。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:21.0000pt;
mso-char-indent-count:2.0000;" ><span><a href="mailto:您可以通过发送电子邮件至service@e-pex.com" ><u><span class="16"  style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
color:rgb(5,99,193);text-decoration:underline;text-underline:single;
font-size:12.0000pt;" ><font face="宋体" >您可以通过发送电子邮件至</font></span></u><u><span class="16"  style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';color:rgb(5,99,193);
text-decoration:underline;text-underline:single;font-size:12.0000pt;" >service@e-pex.com</span></u></a></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >联系客户人员。我</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >们将在</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" >3</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >天内回复您的更正请求</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（五）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >个人信息主体注销账户</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >您随时可注销此前注册的账户，您可以通过</font></span><span><a href="mailto:发送电子邮件至service@e-pex.com" ><u><span class="16"  style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
color:rgb(5,99,193);text-decoration:underline;text-underline:single;
font-size:12.0000pt;" ><font face="宋体" >发送电子邮件至</font></span></u><u><span class="16"  style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';color:rgb(5,99,193);
text-decoration:underline;text-underline:single;font-size:12.0000pt;" >service@e-pex.com</span></u></a></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >联系客户人员。我</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >们将在</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" >3</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >天内回复您的更正请求</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >在技术可行的前提下，例如数据接口匹配，我们还可按您的要求，直接将您的个人信息副本传输给您指定的第三方。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（六）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >约束信息系统自动决策</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >在某些业务功能中，我们可能仅依据信息系统、算法等在内的非人工自动决策机制做出决定。如果这些决定显著影响您的合法权益，您有权要求我们做出解释，我们也将提供适当的救济方式。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:14.2000pt;mso-para-margin-bottom:0.5000gd;
text-indent:7.1000pt;mso-outline-level:2;mso-list:l0 level2 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >（七）<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >响应您的上述请求</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >为保障安全，您可能需要提供书面请求，或以其他方式证明您的身份。我们可能会先要求您验证自己的身份，然后再处理您的请求。我们将在收到您的请求之日起</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" >3</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >天内作出答复。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >对于您合理的请求，我们原则上不收取费用，但对多次重复、超出合理限度的请求，我们将视情况收取一定成本费用。对于那些无端重复、需要过多技术手段（例如，需要开发新系统或从根本上改变现行惯例）、给他人合法权益带来风险或者非常不切实际（例如，涉及备份磁带上存放的信息）的请求，我们可能会予以拒绝。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >在以下情形中，按照法律法规要求，我们将无法响应您的请求：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >15.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >与国家安全、国防安全直接相关的；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >16.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >与公共安全、公共卫生、重大公共利益直接相关的；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >17.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >与犯罪侦查、起诉、审判和判决执行等直接相关的；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >18.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >有充分证据表明您存在主观恶意或滥用权利的；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >19.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >响应您的请求将导致您或其他个人、组织的合法权益受到严重损害的；</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >20.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >涉及商业秘密的。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:0.0000pt;mso-outline-level:1;mso-list:l0 level1 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >五、<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们如何处理儿童的个人信息</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们的服务、网站主要面向成年人（即年满十八周岁的完全民事行为能力人）。如果没有父母或监护人的同意，未成年人不得创建自己的用户账户。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >对于经父母同意而收集未成年人个人信息的情况，我们只会在受到法律允许、父母或监护人明确同意或者保护未成年人所必要的情况下使用或公开披露此信息。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果我们发现自己在未事先获得可证实的父母同意的情况下收集了未成年人的个人信息，则会设法尽快删除相关数据。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:0.0000pt;mso-outline-level:1;mso-list:l0 level1 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >六、<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >您的个人信息如何在全球范围转移</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >原则上，我们在中华人民共和国境内收集和产生的个人信息，将存储在中华人民共和国境内。如您使用跨境交易服务，且需要向境外传输您的个人信息完成交易的，我们会单独征得您的授权同意并要求接收方按照我们的说明、本政策以及其他任何相关的保密和安全措施来处理这些个人信息。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:0.0000pt;mso-outline-level:1;mso-list:l0 level1 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >七、<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >本政策如何更新</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们的隐私政策可能变更。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >未经您明确同意，我们不会削减您按照本隐私政策所应享有的权利。我们会在本页面上发布对本政策所做的任何变更。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >对于重大变更，我们还会提供更为显著的通知（包括对于某些服务，我们会通过电子邮件发送通知，说明隐私政策的具体变更内容）。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >本政策所指的重大变更包括但不限于：</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >21.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们的服务模式发生重大变化。如处理个人信息的目的、处理的个人信息类型、个人信息的使用方式等。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >22.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们在所有权结构、组织架构等方面发生重大变化。如业务调整、破产并购等引起的所有者变更等。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >23.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >个人信息共享、转让或公开披露的主要对象发生变化。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >24.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >您参与个人信息处理方面的权利及其行使方式发生重大变化。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >25.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们负责处理个人信息安全的责任部门、联络方式及投诉渠道发生变化时。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >26.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >个人信息安全影响评估报告表明存在高风险时。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:24.0000pt;
mso-char-indent-count:2.0000;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >我们还会将本政策的旧版本存档，供您查阅。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:0.0000pt;mso-outline-level:1;mso-list:l0 level1 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >八、<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >适用法律和争议解决</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >27.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >本隐私政策的效力、解释、履行和争议解决，均应适用中华人民共和国法律（不包括香港特别行政区、澳门特别行政区与台湾地区法律）。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:21.3000pt;mso-list:l0 level3 lfo4;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >28.<span>&nbsp;</span></span></span><![endif]><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >若您和我们之间发生任何纠纷或争议，</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >双方应通过友好协商解决，若协商解决未果，任何一方均有权将有关纠纷或争议提交由上海仲裁委员会</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >按照其届时有效的仲裁规则予以仲裁，仲裁裁决是终局的且对双方均具有约束力。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;margin-left:0.0000pt;mso-para-margin-bottom:0.5000gd;
text-indent:0.0000pt;mso-outline-level:1;mso-list:l0 level1 lfo1;" ><![if !supportLists]><span style="font-family:宋体;mso-ascii-font-family:'Times New Roman';mso-hansi-font-family:'Times New Roman';
mso-bidi-font-family:'Times New Roman';font-weight:bold;font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><span style='mso-list:Ignore;' >九、<span>&nbsp;</span></span></span><![endif]><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如何联系我们</font></span></b><b><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-weight:bold;font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></b></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:21.0000pt;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果您对本隐私政策有任何疑问、意见或建议，请通过发送邮件至</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" >service@e-pex.</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" >com<font face="宋体" >或拨打我们的</font></span><span style="mso-spacerun:'yes';font-family:宋体;mso-ascii-font-family:'Times New Roman';
mso-hansi-font-family:'Times New Roman';mso-bidi-font-family:'Times New Roman';font-size:12.0000pt;
mso-font-kerning:1.0000pt;" ><font face="宋体" >官网</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >客服电话等多种方式与我们联系。</font> &nbsp;</span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;text-indent:21.0000pt;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ><font face="宋体" >如果您对我们的回复不满意，特别是我们的个人信息处理行为损害了您的合法权益，您还可以通过</font>&#8220;<font face="宋体" >适用法律和争议解决</font><font face="Times New Roman" >&#8221;</font><font face="宋体" >列明的外部途径寻求解决办法。</font></span><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:宋体;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" ></span></p><p class=MsoNormal  style="margin-bottom:7.8000pt;mso-para-margin-bottom:0.5000gd;" ><span style="mso-spacerun:'yes';font-family:'Times New Roman';mso-fareast-font-family:等线;
font-size:12.0000pt;mso-font-kerning:1.0000pt;" >&nbsp;</span></p></div><!--EndFragment--></body>
  </div>
</template>

<script type="text/ecmascript-6">
export default {
  created() {
    this.$store.commit("editIndex", {info: "privateAgreement"});
  },
};
</script>

<style lang="less" scoped></style>
